openapi: 3.0.0
info:
  title: Car Garage API
  version: '1.0'
  description: test
  contact:
    email: admin@example.com
servers:
  - url: 'http://localhost:3000'
paths:
  '/garage/{id}':
    get:
      summary: Get the garage detail and a list of cars
      tags: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the garage
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/responses/GarageResponse'
          description: Sample Response from Garage Endpoint
  '/cars/{id}':
    get:
      summary: Get the detais of a car
      tags: []
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The ID of the car
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CarModel'
      operationId: get-garage-cars-single
      description: test
      security:
        - AwsApiGatewayKey: []
      x-amazon-apigateway-auth:
        type: none
      x-amazon-apigateway-integration:
        uri: 'http://${stageVariables.nlbUrl}/'
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        passthroughBehavior: when_no_match
        connectionType: VPC_LINK
        connectionId: '${stageVariables.vpcLinkId}'
        httpMethod: GET
        type: http_proxy
tags:
  - name: Car Garage
components:
  securitySchemes:
    AwsApiGatewayKey:
      type: apiKey
      in: header
      name: x-api-key
      x-aws-api-id: owuw75mril
  schemas:
    GarageModel:
      $ref: ./common/schemas/GarageModel.v1.yaml
    CarModel:
      $ref: ./common/schemas/CarModel.v1.yaml
  responses:
    GarageResponse:
      $ref: ./common/responses/GarageResponse.yaml
